### ISSUE TITLE
InstancePerTenant dependency and tenants reconfiguration

### ISSUE THREAD

**Issue by gtrubach** [autofac/Autofac.Multitenant#12]
Hello,

This is not an issue but a question. We have a really cool feature such as tenant reconfiguration. But I ran into a problem when using InstancePerTenant dependency with it.

The problem is the following: while tenants dictionary is reconfigured there is a resolve operation in another thread. And when something inner in Autofac receive a lifetime scope than this scope can be disposed in ReconfigureTenant method (since reconfiguration is occured) in another thread. And then DependencyResolutionException occured because scope is disposed but it tries to add disposable InstancePerTenant dependency to stack of disposables. 

And my question is: how can I stay safe in this situation. Thanks for any advise.

**Comment by tillig** [comment]
We have a lock around the scopes to make sure two different threads don't try to configure/reconfigure tenants simultaneously, but for perf reasons we really can't lock the entire set of scopes on resolve to avoid the edge case of someone wanting to reconfigure a tenant on the fly.

If you think about it logically, this is very much like wanting to drop your whole DI container and reconfigure it on the fly in a single-tenant app. It's not something most folks do, and if you do, it's up to you to put the appropriate safeguards around it in your app to make sure things don't go sideways.

I don't have any concrete guidance here and can't imagine a scenario where adding safeguards around that won't cause a perf issue.

- Every use of a specific tenant's scope needs to be somehow wrapped with a read lock. This would happen really early at the composition root. In ASP.NET Core, this would be a super early middleware before `RequestServices` gets generated.
- Any reconfiguration of a tenant scope needs to acquire a write lock based on that read lock.
- You don't want to lock the whole system because one tenant is being reconfigured, so you need some sort of "dictionary of reader-writer locks" where the key is a tenant ID and the value is the reader-writer lock for that tenant.
- Adding a new tenant means adding to that dictionary, so you need a reader-writer lock around that, too, of some nature to ensure the add of the tenant lock to the dictionary and the configuration of the tenant scope happens atomically. (Same thing if you remove tenants.)

It's... non-trivial. And maybe there's a better way to go, something I'm not thinking of, but that's where I'd start.

Obviously, disclaimers: I'm not promising any of that will work, I've not tried it out, and I'm not going to provide any code to illustrate any of that. It's an app-specific need, so... I hope that helps. Good luck.

**Comment by gtrubach** [comment]
Thanks a lot, @tillig.
