### ISSUE TITLE
Upgrade Autofac Multitenant with Asp.Net Core 2.2 to Asp.Net 5

### ISSUE THREAD

**Issue by umar-ulabs** [autofac/Autofac.Multitenant#30]
I have an Asp.Net Core 2.2 application that is currently using following dependencies: 
Autofac: Autofac.AspNetCore.Multitenant version 1.1.0
Autofac.AspNetCore.Extensions version :1.0.2
I want to upgrade the application from from Asp.Net Core 2.2 to Asp.Net 5. Because of the new Generic IHostBuilder and using    AutofacServiceProviderFactory, I am kind of lost as to how to go about building tenants in program.cs and add/remove at runtime. 
in .Net Core 2.2 I am doing it as follows:
``` 
#Program.cs
 var webHost = CreateTenantWebHostBuilder(args)
                   .UseAutofacMultiTenant()
                   .UseStartup<Startup>()
                    .Build();
                    using (var scope = webHost.Services.CreateScope())
                    {
                        try
                        {
                            var applicationLifetime = scope.ServiceProvider
                                                           .GetRequiredService<IApplicationLifetime>();
                            var tenantStore = scope.ServiceProvider
                                                   .GetRequiredService<ICustomTenantsStore>();
                            await tenantStore.InitializeTenantsAsync(applicationLifetime
                                .ApplicationStopping);
                        }
                        catch (Exception ex)
                        {
                           
                        }
                    }
await webHost.RunAsync(cancelTokenSource.Token);
```
How can go about initialisation with new  .UseServiceProviderFactory(new AutofacServiceProviderFactory())?
 Thanks

**Comment by tillig** [comment]
Have you [looked at the repository with a working example](https://github.com/autofac/Autofac.AspNetCore.Multitenant/tree/develop/samples/Sandbox.AspNetCore5)?

I'm going to go ahead and close this since there's an example and we're really trying to get usage questions ("How do I...?") over in Stack Overflow as you probably saw from the issue template. Please ask over there and tag `autofac` - we already monitor those questions but can also get you more help from others in the community. Thanks!
