### ISSUE TITLE
Add virtual keyword to MultitenantContainer.ConfigureTenant

### ISSUE THREAD

**Issue by vlad-kurkotov** [autofac/Autofac.Multitenant#31]
## Problem Statement

I am covering the project with unit tests. I have problems in covering of code that uses `MultitenantContainer.ConfigureTenant(object tenantId, Action<ContainerBuilder> configuration)`.

I want to use Setup and Verify features in order to test how my code is dealing with possible exceptions.

## Desired Solution

`public void ConfigureTenant(object tenantId, Action<ContainerBuilder> configuration)`
should become
`public virtual void ConfigureTenant(object tenantId, Action<ContainerBuilder> configuration)`

## Alternatives You've Considered

Or add some support of such behavior to Automock

**Comment by vlad-kurkotov** [comment]
I have a class. The only purpose of this class is to configure tenant in the multitenant container.
@tillig please,

**Comment by tillig** [comment]
It may be that you need to design the method to be more directly testable. Part of TDD is affecting the design, not just covering code paths. It may be that the thing you need can be accomplished in an entirely different way - mocking one of your own components, destructuring or redesigning how you handle things to make them more testable, taking function or action parameters in one of your methods to help you execute code for a test rather than taking a flat object, something like that. You may need to think outside the box here and think about the design - there are many ways to do things.

This might be something good to post to StackOverflow. Much as I would like to work through this with you, we're not consultants and we have to balance the unpaid time helping individuals with the unpaid time resolving other existing issues. I hate to be that way, but it really does boil down to what I can allocate my personal, free, unpaid time toward, and lately... it's sadly very limited.

The net for Autofac is that we don't want to support `ConfigureTenant` as an extension point. While I see that might make some things easier for your specific use case, it would also adds support burden on us long term that we're not currently willing to take on. How you work around that isn't really something I can dive in and personally help with. Again, I'm sorry.
