### ISSUE TITLE
Reconfiguration of tenants in MultitenantContainer

### ISSUE THREAD

**Issue by gtrubach** [autofac/Autofac.Multitenant#5]
Hi!

I have one question about reconfiguration tenants in MultitenantContainer, Now we cannot do it and I see the following lines in source code:
```c#
// The check and [potential] scope creation are locked here to
// ensure atomicity. We don't want to check and then have another
// thread create the lifetime scope behind our backs.
if (this._tenantLifetimeScopes.ContainsKey(tenantId))
{
    throw new InvalidOperationException(string.Format(CultureInfo.CurrentUICulture, Properties.Resources.MultitenantContainer_TenantAlreadyConfigured, tenantId));
}
```
But I think it will be great if we will can create new lifetime scope for tenant with new configuration. And does GC dispose lifetime scope when we will begin new scope for tenant?

So maybe we can do something following:

1. Allow to create new lifetime scope for configured tenants with new configuration?

2. Remove previous lifetime scope for reconfigured tenant?

There was small discussion [here](https://groups.google.com/d/topic/autofac/I9taROZXHoQ/discussion).

**Comment by tillig** [comment]
When we look at adding the ability to reconfigure tenants we should consider how the locking around the tenant scope dictionary works and maybe go to a reader/writer lock of some nature. That said, reconfiguration of tenants shouldn't be something that happens a lot in an app (e.g., something that only happens on a configuration change, not something that happens on every web request) so that should also weigh in.

**Comment by tillig** [comment]
[Pushed this functionality in release 4.1.0.](https://github.com/autofac/Autofac.Multitenant/releases/tag/v4.1.0)
